<div class="pbmit-slider-area">
	<!-- START Slider 01 REVOLUTION SLIDER 6.5.21 -->

	<rs-fullwidth-wrap id="rev_slider_1_1_forcefullwidth" style="margin-top:0px;margin-bottom:0px;"><rs-module-wrap id="rev_slider_1_1_wrapper" data-alias="slider-01" data-source="gallery" style="visibility: visible; background: transparent; padding: 0px; margin: 0px auto; width: 1254px; height: 870px; position: absolute; overflow: visible; left: 0px;"><rs-module id="rev_slider_1_1" style="width: 1254px; height: 870px; max-height: 870px;" data-version="6.5.21" data-idcheck="true" class="revslider-initialised rev_redraw_on_blurfocus" data-slideactive="rs-13">

				<rs-loader class="spinner0 " style="display: none;background-image:url(../images/ajax-loading.gif);">
					<div class="dot1"></div>
					<div class="dot2"></div>
					<div class="bounce1"></div>
					<div class="bounce2"></div>
					<div class="bounce3"></div>
				</rs-loader><rs-arrow style="opacity: 0; transform: translate(20px, -30px); top: 50%; left: 0px;" class="tp-leftarrow tparrows metis"></rs-arrow><rs-arrow style="opacity: 0; transform: translate(-80px, -30px); top: 50%; left: 100%;" class="tp-rightarrow tparrows metis"></rs-arrow><rs-progress style="visibility:hidden;"><rs-progress-bar style="background: rgba(255, 255, 255, 0.5); transform-origin: 0% 50%; transform: translate3d(0px, 0px, 0px) scale(0.1563, 1);"></rs-progress-bar></rs-progress><rs-slides style="visibility: visible; max-height: none; height: 100%; width: 100%; overflow: hidden;">
					<rs-slide style="position: absolute; display: block; overflow: hidden; height: 100%; width: 100%; z-index: 20; opacity: 1; visibility: inherit;" data-key="rs-13" data-title="Slide" data-thumb="<?= get_template_directory_uri()?>/assets/images/homepage-1/blog/blog-01-s.jpg" data-anim="ms:600;r:0;" data-in="o:0;" data-out="a:false;" data-originalindex="1" data-origindex="0" data-description="" data-sba="" data-scroll-based="false" data-owidth="1900" data-oheight="870" data-rspausetimeronce="0" data-isactiveslide="true"><rs-sbg-px><rs-sbg-wrap data-key="rs-13" data-owidth="1900" data-oheight="870"><!--Runtime Modification - Img tag is Still Available for SEO Goals in Source - <img src="<?= get_template_directory_uri()?>/assets/images/homepage-1/blog/blog-01-s.jpg" alt="" class="rev-slidebg tp-rs-img rs-lazyload" data-lazyload="<?= get_template_directory_uri()?>/assets/images/homepage-1/blog/blog-01-s.jpg" data-no-retina="">--><rs-sbg data-lazyload="<?= get_template_directory_uri()?>/assets/images/homepage-1/blog/blog-01-s.jpg" class="" data-bgcolor="transparent" style="width: 100%; height: 100%;" data-src-rs-ref="<?= get_template_directory_uri()?>/assets/images/homepage-1/blog/blog-01-s.jpg"><canvas width="1254" height="870" style="width: 100%; height: 100%; background-color: transparent; opacity: 1; filter: none; transform: translate(0px, 0px);"></canvas></rs-sbg></rs-sbg-wrap></rs-sbg-px>

						<!--
							--><rs-layer-wrap class="rs-parallax-wrap" style="position: absolute; display: block; pointer-events: auto; left: 42px; top: 319px; z-index: 6; visibility: visible; perspective: 601px;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; transform-origin: 50% 50%; overflow: hidden; transform: translate(0px, 0px);"><rs-layer id="slider-7-slide-13-layer-1" data-type="text" data-color="#4f87fb" data-rsp_ch="on" data-xy="xo:30px,30px,28px,30px;yo:319px,319px,169px,49px;" data-text="s:14;l:20;ls:2px;fw:700;a:inherit;" data-vbility="t,t,f,f" data-frame_0="x:-100%;o:1;tp:600;" data-frame_0_mask="u:t;" data-frame_1="tp:600;st:290;sp:1500;sR:290;" data-frame_1_mask="u:t;" data-frame_999="o:0;tp:600;st:w;sR:7210;" style="z-index: 6; font-family: Mulish; text-transform: uppercase; height: auto; width: auto; color: rgb(79, 135, 251); text-decoration: none; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; text-align: inherit; line-height: 20px; letter-spacing: 2px; font-weight: 700; font-size: 14px; transform-origin: 50% 50%; opacity: 1; transform: translate(0px, 0px); visibility: visible;" class="rs-layer" data-idcheck="true" data-stylerecorder="true" data-initialised="true">s Solution
									</rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap><!--

							--><rs-layer-wrap class="rs-parallax-wrap" style="position: absolute; display: block; pointer-events: auto; left: 42px; top: 352px; z-index: 7; visibility: visible; perspective: 601px;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; transform-origin: 50% 50%; overflow: hidden; transform: translate3d(0px, 0px, 0px);"><rs-layer id="slider-7-slide-13-layer-2" data-type="text" data-color="#130947" data-rsp_ch="on" data-xy="xo:30px,30px,34px,25px;yo:352px,352px,213px,131px;" data-text="s:55,55,34,24;l:60,60,44,30;ls:-1px;fw:900;a:inherit;" data-frame_0="x:-100%;o:1;tp:600;" data-frame_0_mask="u:t;" data-frame_1="tp:600;st:1080;sp:1500;sR:1080;" data-frame_1_mask="u:t;" data-frame_999="o:0;tp:600;st:w;sR:6420;" style="z-index: 7; font-family: Mulish; height: auto; width: auto; color: rgb(19, 9, 71); text-decoration: none; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; text-align: inherit; line-height: 60px; letter-spacing: -1px; font-weight: 900; font-size: 55px; transform-origin: 50% 50%; opacity: 1; transform: translate3d(-217.685px, 0px, 0px); visibility: visible;" class="rs-layer" data-idcheck="true" data-stylerecorder="true" data-initialised="true">Take the<span class="thsn-skincolor" data-stylerecorder="true" style="text-align: inherit; line-height: 60px; letter-spacing: -1px; font-weight: 900; font-size: 55px;">
											world's</span> best<br>
										Quality Treatment.
									</rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap><!--

							--><rs-layer-wrap class="rs-parallax-wrap rs-forcehidden" style="position: absolute; display: block; pointer-events: none; left: 46px; top: 466px; z-index: 5; visibility: hidden; perspective: 601px;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; transform-origin: 50% 50%; overflow: hidden; transform: translate(0px, 0px);"><rs-layer id="slider-7-slide-13-layer-3" class="tp-shape tp-shapewrapper rs-layer" data-type="shape" data-rsp_ch="on" data-xy="xo:34px,34px,38px,29px;yo:466px,466px,298px,188px;" data-text="fw:900;a:inherit;" data-dim="w:170px,170px,110px,75px;h:5px,5px,4px,3px;" data-frame_0="x:-100%;o:1;tp:600;" data-frame_0_mask="u:t;" data-frame_1="tp:600;st:1900;sp:1500;sR:1900;" data-frame_1_mask="u:t;" data-frame_999="o:0;tp:600;st:w;sR:5600;" style="z-index: 5; background-color: rgb(79, 135, 251); color: rgb(255, 255, 255); width: 170px; height: 5px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; transform-origin: 50% 50%; opacity: 1; transform: translate(-170px, 0px); visibility: visible;" data-idcheck="true" data-stylerecorder="true" data-initialised="true">
									</rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap><!--

							--><rs-layer-wrap class="rs-parallax-wrap rs-forcehidden" style="position: absolute; display: block; pointer-events: none; left: 42px; top: 527px; z-index: 8; visibility: hidden; perspective: 601px;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; overflow: visible;"><a id="slider-7-slide-13-layer-4" class="rs-layer rev-btn" href="http://dentiq-demo.pbminfotech.com/demo1/contact-us/" target="_self" rel="nofollow" data-type="button" data-color="rgba(255,255,255,1)" data-rsp_ch="on" data-xy="xo:30px,30px,39px,26px;yo:527px,527px,324px,207px;" data-text="s:13,13,7,4;l:26,26,15,9;ls:1px,1px,0px,0px;fw:700;a:inherit;" data-padding="t:15,15,9,6;r:40,40,25,15;b:15,15,9,6;l:40,40,25,15;" data-border="bor:4px,4px,4px,4px;" data-frame_0="tp:600;" data-frame_1="tp:600;st:3000;sp:500;sR:3000;" data-frame_999="o:0;tp:600;st:w;sR:5500;" data-frame_hover="bgc:#130947;boc:#000;bor:3px,3px,3px,3px;bos:solid;oX:50;oY:50;sp:0;" style="z-index: 8; background-color: rgb(79, 135, 251); font-family: Mulish; cursor: pointer; outline: none; box-shadow: none; box-sizing: border-box; height: auto; width: auto; color: rgb(255, 255, 255); text-decoration: none; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; text-align: inherit; line-height: 26px; letter-spacing: 1px; font-weight: 700; font-size: 13px; border-color: transparent; padding: 15px 40px; border-radius: 4px; transform-origin: 50% 50%; transform: translate(0px, 0px); opacity: 0; visibility: visible;" data-idcheck="true" data-stylerecorder="true" data-initialised="true">CONTACT
										US
									</a></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap><!--

							--><rs-layer-wrap class="rs-parallax-wrap rs-forcehidden" style="position: absolute; display: block; pointer-events: none; left: 210px; top: 509px; z-index: 9; visibility: hidden; perspective: 601px;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; overflow: visible;"><rs-layer id="slider-7-slide-13-layer-5" data-type="image" data-rsp_ch="on" data-xy="xo:198px,198px,198px,109px;yo:509px,509px,509px,156px;" data-text="l:22;a:inherit;" data-dim="w:['109px','109px','109px','109px'];h:['109px','109px','109px','109px'];" data-vbility="t,t,f,f" data-frame_0="tp:600;" data-frame_1="tp:600;st:3510;sp:500;sR:3510;" data-frame_999="o:0;tp:600;st:w;sR:4990;" style="z-index: 9; color: rgb(255, 255, 255); width: 109px; height: 109px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; transform-origin: 50% 50%; transform: translate(0px, 0px); opacity: 0; visibility: visible;" class="rs-layer" data-idcheck="true" data-stylerecorder="true" data-initialised="true"><img src="<?= get_template_directory_uri()?>/assets/revolution/images/slider-icon.png" alt="slider-icon" class="tp-rs-img rs-lazyload" width="109" height="109" data-lazyload="<?= get_template_directory_uri()?>/assets/revolution/images/slider-icon.png" data-no-retina="" data-reference="<?= get_template_directory_uri()?>/assets/revolution/images/slider-icon.png" data-src-rs-ref="<?= get_template_directory_uri()?>/assets/revolution/images/slider-icon.png" style="position: relative; height: 100%; width: 100%;">
									</rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap><!--

							--><rs-layer-wrap class="rs-parallax-wrap rs-forcehidden" style="position: absolute; display: block; pointer-events: none; left: 310px; top: 545px; z-index: 10; visibility: hidden; perspective: 601px;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; overflow: visible;"><a id="slider-7-slide-13-layer-6" class="rs-layer" href="http://dentiq-demo.pbminfotech.com/demo1/make-appointments/" target="_self" rel="nofollow" data-type="text" data-color="#130947" data-rsp_ch="on" data-xy="xo:298px;yo:545px;" data-text="s:13;l:22;fw:800;a:inherit;" data-vbility="t,t,f,f" data-frame_0="tp:600;" data-frame_1="tp:600;st:3560;sp:500;sR:3560;" data-frame_999="o:0;tp:600;st:w;sR:4940;" style="z-index: 10; font-family: Mulish; text-transform: uppercase; height: auto; width: auto; color: rgb(19, 9, 71); text-decoration: none; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; text-align: inherit; line-height: 22px; letter-spacing: 0px; font-weight: 800; font-size: 13px; transform-origin: 50% 50%; transform: translate(0px, 0px); opacity: 0; visibility: visible;" data-idcheck="true" data-stylerecorder="true" data-initialised="true">Get Free Checkup
									</a></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap><!--
--> </rs-slide>
					<rs-slide style="position: absolute; display: none; overflow: hidden; height: 100%; width: 100%; z-index: 10; opacity: 1; visibility: inherit;" data-key="rs-20" data-title="Slide" data-thumb="<?= get_template_directory_uri()?>/assets/images/homepage-1/blog/blog-02-s.jpg" data-anim="ms:600;r:0;" data-in="o:0;" data-out="a:false;" data-originalindex="2" data-origindex="1" data-description="" data-sba="" data-scroll-based="false" data-owidth="1900" data-oheight="870" data-rspausetimeronce="0" data-isactiveslide="false"><rs-sbg-px><rs-sbg-wrap data-key="rs-20" data-owidth="1900" data-oheight="870"><!--Runtime Modification - Img tag is Still Available for SEO Goals in Source - <img src="<?= get_template_directory_uri()?>/assets/images/homepage-1/blog/blog-02-s.jpg" alt="" title="slider1-02" width="1900" height="870" class="rev-slidebg tp-rs-img rs-lazyload" data-lazyload="<?= get_template_directory_uri()?>/assets/images/homepage-1/blog/blog-02-s.jpg" data-no-retina="">--><rs-sbg data-lazyload="<?= get_template_directory_uri()?>/assets/images/homepage-1/blog/blog-02-s.jpg" class="" data-bgcolor="transparent" style="width: 100%; height: 100%;" data-src-rs-ref="<?= get_template_directory_uri()?>/assets/images/homepage-1/blog/blog-02-s.jpg"><canvas width="1254" height="870" style="width: 100%; height: 100%; background-color: transparent; opacity: 1; filter: none; transform: translate(0px, 0px);"></canvas></rs-sbg></rs-sbg-wrap></rs-sbg-px>

						<!--
							--><rs-layer-wrap class="rs-parallax-wrap rs-forcehidden" style="position: absolute; display: block; pointer-events: none; left: 42px; top: 319px; z-index: 6; visibility: hidden; perspective: 601px;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; transform-origin: 50% 50%; overflow: visible;"><rs-layer id="slider-7-slide-20-layer-1" data-type="text" data-color="#4f87fb" data-rsp_ch="on" data-xy="xo:30px,30px,28px,30px;yo:319px,319px,169px,49px;" data-text="s:14;l:20;ls:2px;fw:700;a:inherit;" data-vbility="t,t,f,f" data-frame_0="x:-100%;o:1;tp:600;" data-frame_0_mask="u:t;" data-frame_1="tp:600;st:290;sp:1500;sR:290;" data-frame_1_mask="u:t;" data-frame_999="o:0;tp:600;st:w;sR:7210;" style="z-index: 6; font-family: Mulish; text-transform: uppercase; height: auto; width: auto; color: rgb(79, 135, 251); text-decoration: none; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; text-align: inherit; line-height: 20px; letter-spacing: 2px; font-weight: 700; font-size: 14px; transform-origin: 50% 50%; opacity: 0; transform: translate(0px, 0px); visibility: visible;" class="rs-layer" data-idcheck="true" data-stylerecorder="true" data-initialised="true">Online Solution
									</rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap><!--

							--><rs-layer-wrap class="rs-parallax-wrap rs-forcehidden" style="position: absolute; display: block; pointer-events: none; left: 42px; top: 352px; z-index: 7; visibility: hidden; perspective: 601px;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; transform-origin: 50% 50%; overflow: visible;"><rs-layer id="slider-7-slide-20-layer-2" data-type="text" data-color="#130947" data-rsp_ch="on" data-xy="xo:30px,30px,34px,25px;yo:352px,352px,213px,131px;" data-text="s:55,55,34,24;l:60,60,44,30;ls:-1px;fw:900;a:inherit;" data-frame_0="x:-100%;o:1;tp:600;" data-frame_0_mask="u:t;" data-frame_1="tp:600;st:1080;sp:1500;sR:1080;" data-frame_1_mask="u:t;" data-frame_999="o:0;tp:600;st:w;sR:6420;" style="z-index: 7; font-family: Mulish; height: auto; width: auto; color: rgb(19, 9, 71); text-decoration: none; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; text-align: inherit; line-height: 60px; letter-spacing: -1px; font-weight: 900; font-size: 55px; transform-origin: 50% 50%; opacity: 0; transform: translate(0px, 0px); visibility: visible;" class="rs-layer" data-idcheck="true" data-stylerecorder="true" data-initialised="true">Take the<span class="thsn-skincolor" data-stylerecorder="true" style="text-align: inherit; line-height: 60px; letter-spacing: -1px; font-weight: 900; font-size: 55px;">
											world's</span> best<br>
										Quality Treatment.
									</rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap><!--

							--><rs-layer-wrap class="rs-parallax-wrap rs-forcehidden" style="position: absolute; display: block; pointer-events: none; left: 46px; top: 466px; z-index: 5; visibility: hidden; perspective: 601px;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; transform-origin: 50% 50%; overflow: visible;"><rs-layer id="slider-7-slide-20-layer-3" class="tp-shape tp-shapewrapper rs-layer" data-type="shape" data-rsp_ch="on" data-xy="xo:34px,34px,38px,29px;yo:466px,466px,298px,188px;" data-text="fw:900;a:inherit;" data-dim="w:170px,170px,110px,75px;h:5px,5px,4px,3px;" data-frame_0="x:-100%;o:1;tp:600;" data-frame_0_mask="u:t;" data-frame_1="tp:600;st:1900;sp:1500;sR:1900;" data-frame_1_mask="u:t;" data-frame_999="o:0;tp:600;st:w;sR:5600;" style="z-index: 5; background-color: rgb(79, 135, 251); color: rgb(255, 255, 255); width: 170px; height: 5px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; transform-origin: 50% 50%; opacity: 0; transform: translate(0px, 0px); visibility: visible;" data-idcheck="true" data-stylerecorder="true" data-initialised="true">
									</rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap><!--

							--><rs-layer-wrap class="rs-parallax-wrap rs-forcehidden" style="position: absolute; display: block; pointer-events: none; left: 42px; top: 527px; z-index: 8; visibility: hidden; perspective: 601px;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; overflow: visible;"><a id="slider-7-slide-20-layer-4" class="rs-layer rev-btn" href="http://dentiq-demo.pbminfotech.com/demo1/contact-us/" target="_self" rel="nofollow" data-type="button" data-color="rgba(255,255,255,1)" data-rsp_ch="on" data-xy="xo:30px,30px,39px,26px;yo:527px,527px,324px,207px;" data-text="s:13,13,7,4;l:26,26,15,9;ls:1px,1px,0px,0px;fw:700;a:inherit;" data-padding="t:15,15,9,6;r:40,40,25,15;b:15,15,9,6;l:40,40,25,15;" data-border="bor:4px,4px,4px,4px;" data-frame_0="tp:600;" data-frame_1="tp:600;st:3000;sp:500;sR:3000;" data-frame_999="o:0;tp:600;st:w;sR:5500;" data-frame_hover="bgc:#130947;boc:#000;bor:3px,3px,3px,3px;bos:solid;oX:50;oY:50;sp:0;" style="z-index: 8; background-color: rgb(79, 135, 251); font-family: Mulish; cursor: pointer; outline: none; box-shadow: none; box-sizing: border-box; height: auto; width: auto; color: rgb(255, 255, 255); text-decoration: none; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; text-align: inherit; line-height: 26px; letter-spacing: 1px; font-weight: 700; font-size: 13px; border-color: transparent; padding: 15px 40px; border-radius: 4px; transform-origin: 50% 50%; transform: translate(0px, 0px); opacity: 0; visibility: visible;" data-idcheck="true" data-stylerecorder="true" data-initialised="true">CONTACT
										US
									</a></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap><!--

							--><rs-layer-wrap class="rs-parallax-wrap rs-forcehidden" style="position: absolute; display: block; pointer-events: none; left: 210px; top: 509px; z-index: 9; visibility: hidden; perspective: 601px;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; overflow: visible;"><rs-layer id="slider-7-slide-20-layer-5" data-type="image" data-rsp_ch="on" data-xy="xo:198px,198px,198px,109px;yo:509px,509px,509px,156px;" data-text="l:22;a:inherit;" data-dim="w:['109px','109px','109px','109px'];h:['109px','109px','109px','109px'];" data-vbility="t,t,f,f" data-frame_0="tp:600;" data-frame_1="tp:600;st:3510;sp:500;sR:3510;" data-frame_999="o:0;tp:600;st:w;sR:4990;" style="z-index: 9; color: rgb(255, 255, 255); width: 109px; height: 109px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; transform-origin: 50% 50%; transform: translate(0px, 0px); opacity: 0; visibility: visible;" class="rs-layer" data-idcheck="true" data-stylerecorder="true" data-initialised="true"><img src="<?= get_template_directory_uri()?>/assets/revolution/images/slider-icon.png" alt="slider-icon" class="tp-rs-img rs-lazyload" width="109" height="109" data-lazyload="<?= get_template_directory_uri()?>/assets/revolution/images/slider-icon.png" data-no-retina="" data-src-rs-ref="<?= get_template_directory_uri()?>/assets/revolution/images/slider-icon.png" style="position: relative; height: 100%; width: 100%;">
									</rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap><!--

							--><rs-layer-wrap class="rs-parallax-wrap rs-forcehidden" style="position: absolute; display: block; pointer-events: none; left: 310px; top: 545px; z-index: 10; visibility: hidden; perspective: 601px;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; overflow: visible;"><a id="slider-7-slide-20-layer-6" class="rs-layer" href="http://dentiq-demo.pbminfotech.com/demo1/make-appointments/" target="_self" rel="nofollow" data-type="text" data-color="#130947" data-rsp_ch="on" data-xy="xo:298px;yo:545px;" data-text="s:13;l:22;fw:800;a:inherit;" data-vbility="t,t,f,f" data-frame_0="tp:600;" data-frame_1="tp:600;st:3560;sp:500;sR:3560;" data-frame_999="o:0;tp:600;st:w;sR:4940;" style="z-index: 10; font-family: Mulish; text-transform: uppercase; height: auto; width: auto; color: rgb(19, 9, 71); text-decoration: none; white-space: nowrap; min-height: 0px; min-width: 0px; max-height: none; max-width: none; text-align: inherit; line-height: 22px; letter-spacing: 0px; font-weight: 800; font-size: 13px; transform-origin: 50% 50%; transform: translate(0px, 0px); opacity: 0; visibility: visible;" data-idcheck="true" data-stylerecorder="true" data-initialised="true">Get Free Checkup
									</a></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap><!--
--> </rs-slide>
				</rs-slides></rs-module>

		</rs-module-wrap><rs-fw-forcer style="height:870px"></rs-fw-forcer></rs-fullwidth-wrap>
	<!-- END REVOLUTION SLIDER -->
</div>